# Generated by Django 4.1.2 on 2022-11-18 23:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcondition',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 23, 43, 16, 78068, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 23, 43, 16, 77067, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermedicalcondition',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 23, 43, 16, 78068, tzinfo=datetime.timezone.utc)),
        ),
    ]
