# Generated by Django 4.1.3 on 2022-11-19 00:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_medicalcondition_created_alter_profile_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fragrance_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 0, 53, 8, 486694, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 0, 53, 8, 485679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usermedicalcondition',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 0, 53, 8, 486694, tzinfo=datetime.timezone.utc)),
        ),
    ]
